default_context:
  project_name: 'dating'
  project_slug: 'dating'
  domain_main: 'dating.com'
  domain_staging: 'stag.dating.com'
  docker_swarm_stack_name_main: 'dating-com'
  docker_swarm_stack_name_staging: 'stag-dating-com'
  secret_key: 'b28aa4e0e67cd1811e47bf3ea7ecbf5d68a0dc457ed1a28da461cb861e060881'
  first_superuser: 'admin@dating.com'
  first_superuser_password: 'c09aa4aec46f8f51ad1c1252c8ed1d0e2d48e4580e821e05835a3908775ab5ef'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.dating.com", "https://stag.dating.com", "https://dating.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@dating.com'
  postgres_password: '706ff91208d707dafce253'
  pgadmin_default_user: 'admin@dating.com'
  pgadmin_default_user_password: 'c09aa4aec46f8f51ad1c1252c8ed1d0e2d48e4580e821e05835a3908775ab5ef'
  traefik_constraint_tag: 'dating.com'
  traefik_constraint_tag_staging: 'stag.dating.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:c09aa4aec46f8f51ad1c1252c8ed1d0e2d48e4580e821e05835a3908775ab5ef'
  sentry_dsn: 'https://6aebc7cad39f44bc9b308791043184f0@o527812.ingest.sentry.io/5644536'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
