"""Add new rows to user profile table.

Revision ID: 3dc3cb88b8fa
Revises: a67bcd1dd219
Create Date: 2021-03-07 21:09:06.064575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc3cb88b8fa'
down_revision = 'a67bcd1dd219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('age', sa.SmallInteger(), nullable=True))
    op.add_column('userprofile', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'description')
    op.drop_column('userprofile', 'age')
    # ### end Alembic commands ###
