"""Add fields for user filter to UserProfile

Revision ID: b0b6fdc543b1
Revises: 67c001fd690a
Create Date: 2021-06-19 15:39:43.795747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b6fdc543b1'
down_revision = '67c001fd690a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('preferred_age_max', sa.Integer(), nullable=True))
    op.add_column('userprofile', sa.Column('preferred_age_min', sa.Integer(), nullable=True))
    op.add_column('userprofile', sa.Column('preferred_gender', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'preferred_gender')
    op.drop_column('userprofile', 'preferred_age_min')
    op.drop_column('userprofile', 'preferred_age_max')
    # ### end Alembic commands ###
